In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('ambiguous_fitness_dataset.csv')

In [6]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60    26-12-2020    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

**1. Shape:**

It returns a Tuple(rows,columns) representing the DataFrame size.It is used to quickly check the dimension of the dataset.

In [7]:
df.shape

(32, 5)

**2. Index:**

It returns the range of the index of your DataFrame. It is used to quickly check the dimension of the Dataset.

In [8]:
df.index

RangeIndex(start=0, stop=32, step=1)

**3. columns:**

It will list all the Column Names of your DataFrame.

In [9]:
df.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='str')

**4. count():**

Counts non-null for each columns. Missing values are excluded from the Count Function.

In [10]:
df.count()

Duration    32
Date        31
Pulse       32
Maxpulse    32
Calories    30
dtype: int64

**5. sum():**

It Sums each Numerical Column seperately.

In [11]:
df.sum(numeric_only = True)

Duration    2190.0
Pulse       3312.0
Maxpulse    4112.0
Calories    9140.4
dtype: float64

In [12]:
df[['Pulse','Maxpulse','Calories','Duration']].sum()

Pulse       3312.0
Maxpulse    4112.0
Calories    9140.4
Duration    2190.0
dtype: float64

**6. min():**

It returns the smallest value in each column.

In [13]:
df.min(numeric_only = True)

Duration     30.0
Pulse        90.0
Maxpulse    101.0
Calories    195.1
dtype: float64

**7. max():**

It returns the maximum value in each column.

In [14]:
df.max(numeric_only = True)

Duration    450.0
Pulse       130.0
Maxpulse    175.0
Calories    479.0
dtype: float64

**8. describe():**

By default, It provides Statistical Summary of the Numerical columns like Count, Mean, Std, min, max, quartiles.

In [15]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [16]:
df.describe(include = 'all')

          Duration          Date       Pulse    Maxpulse    Calories
count    32.000000            31   32.000000   32.000000   30.000000
unique         NaN            30         NaN         NaN         NaN
top            NaN  '2020/12/12'         NaN         NaN         NaN
freq           NaN             2         NaN         NaN         NaN
mean     68.437500           NaN  103.500000  128.500000  304.680000
std      70.039591           NaN    7.832933   12.998759   66.003779
min      30.000000           NaN   90.000000  101.000000  195.100000
25%      60.000000           NaN  100.000000  120.000000  250.700000
50%      60.000000           NaN  102.500000  127.500000  291.200000
75%      60.000000           NaN  106.500000  132.250000  343.975000
max     450.000000           NaN  130.000000  175.000000  479.000000

**9. mean():**

In [17]:
df.mean(numeric_only = True)

Duration     68.4375
Pulse       103.5000
Maxpulse    128.5000
Calories    304.6800
dtype: float64

In [18]:
df['Pulse'].mean()

np.float64(103.5)

In [19]:
df[['Pulse','Duration']].mean()

Pulse       103.5000
Duration     68.4375
dtype: float64

**10. median():**

It returns the middle most value after sorting the data columns.

In [20]:
df.median(numeric_only = True)

Duration     60.0
Pulse       102.5
Maxpulse    127.5
Calories    291.2
dtype: float64

In [21]:
print(df['Pulse'].median())

102.5

In [22]:
df[['Pulse','Duration']].median()

Pulse       102.5
Duration     60.0
dtype: float64

**11. mode():**

It returns the most frequently Occuring value of the data column.

In [23]:
df.mode()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/12'    100       120     300.0

In [24]:
print(df['Date'].mode())

0    '2020/12/12'
Name: Date, dtype: str

In [25]:
df[['Pulse','Duration']].mode()

   Pulse  Duration
0    100        60

**12. info():**

It Shows the Summary of your dataset which includes column names, non-null counts, data types of each columns and memory usage also. It is Good for spotting the overall view of your dataset at once.

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     str
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), str(1)
memory usage: 1.7 KB

**13. head():**

It will show the top 5 rows of your dataset by default.

In [27]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [28]:
df.head(2)

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0

**14. tail():**

It will show the bottom 5 rows by default.

In [29]:
df.tail()

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [30]:
df.tail(2)

    Duration          Date  Pulse  Maxpulse  Calories
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

**15. dtypes:**

It shows the datatypes of each column.

In [31]:
df.dtypes

Duration      int64
Date            str
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

**16. value_counts():**

It will count the frequency of Unique value in the columns.

In [32]:
df['Duration'].value_counts().sort_index()

Duration
30      1
45      6
60     24
450     1
Name: count, dtype: int64

**17. unique():**

Unique Shows the distinct values in the form of arrays.

In [33]:
df['Duration'].unique()

array([ 60,  45, 450,  30])

**18. nunique():**

Nunique will count the number of unique values in the column.

In [34]:
df['Duration'].nunique()

4

**19. sort_values():**

Sort datasets on the basis of a Provided Column.

In [35]:
df.sort_values(by = "Pulse",ascending = False) # by default it sorts in a ascending order only , but if we want it to aort in descending order then use -> ascending = False.

    Duration          Date  Pulse  Maxpulse  Calories
23        60  '2020/12/23'    130       101     300.0
1         60  '2020/12/02'    117       145     479.0
4         45  '2020/12/05'    117       148     406.0
6         60  '2020/12/07'    110       136     374.0
0         60  '2020/12/01'    110       130     409.1
3         45  '2020/12/04'    109       175     282.4
8         30  '2020/12/09'    109       133     195.1
21        60  '2020/12/21'    108       131     364.2
13        60  '2020/12/13'    106       128     345.3
24        45  '2020/12/24'    105       132     246.0
14        60  '2020/12/14'    104       132     379.3
7        450  '2020/12/08'    104       134     253.3
19        60  '2020/12/19'    103       123     323.0
2         60  '2020/12/03'    103       135     340.0
10        60  '2020/12/11'    103       147     329.3
28        60  '2020/12/28'    103       132       NaN
5         60  '2020/12/06'    102       127     300.0
30        60  '2020/12/30'    102       129     380.3
25        60  '2020/12/25'    102       126     334.5
12        60  '2020/12/12'    100       120     250.7
29        60  '2020/12/29'    100       132     280.0
26        60    26-12-2020    100       120     250.0
11        60  '2020/12/12'    100       120     250.7
17        60  '2020/12/17'    100       120     300.0
22        45           NaN    100       119     282.0
9         60  '2020/12/10'     98       124     269.0
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
20        45  '2020/12/20'     97       125     243.0
27        60  '2020/12/27'     92       118     241.0
31        60  '2020/12/31'     92       115     243.0
18        45  '2020/12/18'     90       112       NaN

**20. isnull():**

This function detects the missing values in the form of Binary Values (True/False), i.e, If the value is present then it gives False, and if the Null value is there then True

In [36]:
df.isnull()

    Duration   Date  Pulse  Maxpulse  Calories
0      False  False  False     False     False
1      False  False  False     False     False
2      False  False  False     False     False
3      False  False  False     False     False
4      False  False  False     False     False
5      False  False  False     False     False
6      False  False  False     False     False
7      False  False  False     False     False
8      False  False  False     False     False
9      False  False  False     False     False
10     False  False  False     False     False
11     False  False  False     False     False
12     False  False  False     False     False
13     False  False  False     False     False
14     False  False  False     False     False
15     False  False  False     False     False
16     False  False  False     False     False
17     False  False  False     False     False
18     False  False  False     False      True
19     False  False  False     False     False
20     False  False  False     False     False
21     False  False  False     False     False
22     False   True  False     False     False
23     False  False  False     False     False
24     False  False  False     False     False
25     False  False  False     False     False
26     False  False  False     False     False
27     False  False  False     False     False
28     False  False  False     False      True
29     False  False  False     False     False
30     False  False  False     False     False
31     False  False  False     False     False

In [37]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

**21. notnull():**

If the values are present then it will give you True, and if not present then it returns False.

In [38]:
df.notnull()

    Duration   Date  Pulse  Maxpulse  Calories
0       True   True   True      True      True
1       True   True   True      True      True
2       True   True   True      True      True
3       True   True   True      True      True
4       True   True   True      True      True
5       True   True   True      True      True
6       True   True   True      True      True
7       True   True   True      True      True
8       True   True   True      True      True
9       True   True   True      True      True
10      True   True   True      True      True
11      True   True   True      True      True
12      True   True   True      True      True
13      True   True   True      True      True
14      True   True   True      True      True
15      True   True   True      True      True
16      True   True   True      True      True
17      True   True   True      True      True
18      True   True   True      True     False
19      True   True   True      True      True
20      True   True   True      True      True
21      True   True   True      True      True
22      True  False   True      True      True
23      True   True   True      True      True
24      True   True   True      True      True
25      True   True   True      True      True
26      True   True   True      True      True
27      True   True   True      True      True
28      True   True   True      True     False
29      True   True   True      True      True
30      True   True   True      True      True
31      True   True   True      True      True

In [39]:
df.notnull().sum()

Duration    32
Date        31
Pulse       32
Maxpulse    32
Calories    30
dtype: int64

**22. dropna():**

This Function is used to remove the missing value(NaN, None,NaT) rows from the DataFrame or Series

In [40]:
df.dropna()

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60    26-12-2020    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

**23. fillna():**

The fillna() function in pandas is used to fill the missing values by using the Imputation techniques.

In [41]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60    26-12-2020    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [42]:
df = df.fillna({
    'Calories':df['Calories'].mean()
})
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
22        45           NaN    100       119    282.00
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60    26-12-2020    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

In [43]:
df = df.fillna({
    'Date':df['Date'].mode()[0]
})
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
22        45  '2020/12/12'    100       119    282.00
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60    26-12-2020    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

In [44]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
22        45  '2020/12/12'    100       119    282.00
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60    26-12-2020    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

**24. drop_duplicates():**

The drop_duplicates() function removes the duplicate rows from a DataFrame.

**i) Exact match:**

In [45]:
df.drop_duplicates(inplace = True)

In [46]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
22        45  '2020/12/12'    100       119    282.00
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60    26-12-2020    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

**ii) Removing the duplicacy based on a Single column:**

In [47]:
df.drop_duplicates('Duration')

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
3        45  '2020/12/04'    109       175     282.4
7       450  '2020/12/08'    104       134     253.3
8        30  '2020/12/09'    109       133     195.1

**iii) Removing the duplicacy based on Multiple columns:**

In [48]:
df.drop_duplicates(subset = ['Calories','Duration'])

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
22        45  '2020/12/12'    100       119    282.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60    26-12-2020    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

**25. astype():**

It will allow us to change the datatype of a Column.

In [49]:
df.dtypes

Duration      int64
Date            str
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [50]:
df['Maxpulse'] = df['Maxpulse'].astype(float)

In [51]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110     130.0    409.10
1         60  '2020/12/02'    117     145.0    479.00
2         60  '2020/12/03'    103     135.0    340.00
3         45  '2020/12/04'    109     175.0    282.40
4         45  '2020/12/05'    117     148.0    406.00
5         60  '2020/12/06'    102     127.0    300.00
6         60  '2020/12/07'    110     136.0    374.00
7        450  '2020/12/08'    104     134.0    253.30
8         30  '2020/12/09'    109     133.0    195.10
9         60  '2020/12/10'     98     124.0    269.00
10        60  '2020/12/11'    103     147.0    329.30
11        60  '2020/12/12'    100     120.0    250.70
13        60  '2020/12/13'    106     128.0    345.30
14        60  '2020/12/14'    104     132.0    379.30
15        60  '2020/12/15'     98     123.0    275.00
16        60  '2020/12/16'     98     120.0    215.20
17        60  '2020/12/17'    100     120.0    300.00
18        45  '2020/12/18'     90     112.0    304.68
19        60  '2020/12/19'    103     123.0    323.00
20        45  '2020/12/20'     97     125.0    243.00
21        60  '2020/12/21'    108     131.0    364.20
22        45  '2020/12/12'    100     119.0    282.00
23        60  '2020/12/23'    130     101.0    300.00
24        45  '2020/12/24'    105     132.0    246.00
25        60  '2020/12/25'    102     126.0    334.50
26        60    26-12-2020    100     120.0    250.00
27        60  '2020/12/27'     92     118.0    241.00
28        60  '2020/12/28'    103     132.0    304.68
29        60  '2020/12/29'    100     132.0    280.00
30        60  '2020/12/30'    102     129.0    380.30
31        60  '2020/12/31'     92     115.0    243.00

In [52]:
df.dtypes

Duration      int64
Date            str
Pulse         int64
Maxpulse    float64
Calories    float64
dtype: object

**26. replace():**

The replace() is used to replace the specific values in a DataFrame with Other Values.

In [53]:
df['Date'] = df['Date'].replace('26-12-2020','2020/12/26')
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110     130.0    409.10
1         60  '2020/12/02'    117     145.0    479.00
2         60  '2020/12/03'    103     135.0    340.00
3         45  '2020/12/04'    109     175.0    282.40
4         45  '2020/12/05'    117     148.0    406.00
5         60  '2020/12/06'    102     127.0    300.00
6         60  '2020/12/07'    110     136.0    374.00
7        450  '2020/12/08'    104     134.0    253.30
8         30  '2020/12/09'    109     133.0    195.10
9         60  '2020/12/10'     98     124.0    269.00
10        60  '2020/12/11'    103     147.0    329.30
11        60  '2020/12/12'    100     120.0    250.70
13        60  '2020/12/13'    106     128.0    345.30
14        60  '2020/12/14'    104     132.0    379.30
15        60  '2020/12/15'     98     123.0    275.00
16        60  '2020/12/16'     98     120.0    215.20
17        60  '2020/12/17'    100     120.0    300.00
18        45  '2020/12/18'     90     112.0    304.68
19        60  '2020/12/19'    103     123.0    323.00
20        45  '2020/12/20'     97     125.0    243.00
21        60  '2020/12/21'    108     131.0    364.20
22        45  '2020/12/12'    100     119.0    282.00
23        60  '2020/12/23'    130     101.0    300.00
24        45  '2020/12/24'    105     132.0    246.00
25        60  '2020/12/25'    102     126.0    334.50
26        60    2020/12/26    100     120.0    250.00
27        60  '2020/12/27'     92     118.0    241.00
28        60  '2020/12/28'    103     132.0    304.68
29        60  '2020/12/29'    100     132.0    280.00
30        60  '2020/12/30'    102     129.0    380.30
31        60  '2020/12/31'     92     115.0    243.00

In [54]:
df['Date'] = pd.to_datetime(df['Date'].astype(str).str.replace("'",""))
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110     130.0    409.10
1         60 2020-12-02    117     145.0    479.00
2         60 2020-12-03    103     135.0    340.00
3         45 2020-12-04    109     175.0    282.40
4         45 2020-12-05    117     148.0    406.00
5         60 2020-12-06    102     127.0    300.00
6         60 2020-12-07    110     136.0    374.00
7        450 2020-12-08    104     134.0    253.30
8         30 2020-12-09    109     133.0    195.10
9         60 2020-12-10     98     124.0    269.00
10        60 2020-12-11    103     147.0    329.30
11        60 2020-12-12    100     120.0    250.70
13        60 2020-12-13    106     128.0    345.30
14        60 2020-12-14    104     132.0    379.30
15        60 2020-12-15     98     123.0    275.00
16        60 2020-12-16     98     120.0    215.20
17        60 2020-12-17    100     120.0    300.00
18        45 2020-12-18     90     112.0    304.68
19        60 2020-12-19    103     123.0    323.00
20        45 2020-12-20     97     125.0    243.00
21        60 2020-12-21    108     131.0    364.20
22        45 2020-12-12    100     119.0    282.00
23        60 2020-12-23    130     101.0    300.00
24        45 2020-12-24    105     132.0    246.00
25        60 2020-12-25    102     126.0    334.50
26        60 2020-12-26    100     120.0    250.00
27        60 2020-12-27     92     118.0    241.00
28        60 2020-12-28    103     132.0    304.68
29        60 2020-12-29    100     132.0    280.00
30        60 2020-12-30    102     129.0    380.30
31        60 2020-12-31     92     115.0    243.00

In [57]:
mean_value = df.loc[df['Duration'] != 450,'Duration'].mean()

In [59]:
print(mean_value)

56.0

In [60]:
df['Duration'] = df['Duration'].replace(450,mean_value)

In [61]:
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110     130.0    409.10
1         60 2020-12-02    117     145.0    479.00
2         60 2020-12-03    103     135.0    340.00
3         45 2020-12-04    109     175.0    282.40
4         45 2020-12-05    117     148.0    406.00
5         60 2020-12-06    102     127.0    300.00
6         60 2020-12-07    110     136.0    374.00
7         56 2020-12-08    104     134.0    253.30
8         30 2020-12-09    109     133.0    195.10
9         60 2020-12-10     98     124.0    269.00
10        60 2020-12-11    103     147.0    329.30
11        60 2020-12-12    100     120.0    250.70
13        60 2020-12-13    106     128.0    345.30
14        60 2020-12-14    104     132.0    379.30
15        60 2020-12-15     98     123.0    275.00
16        60 2020-12-16     98     120.0    215.20
17        60 2020-12-17    100     120.0    300.00
18        45 2020-12-18     90     112.0    304.68
19        60 2020-12-19    103     123.0    323.00
20        45 2020-12-20     97     125.0    243.00
21        60 2020-12-21    108     131.0    364.20
22        45 2020-12-12    100     119.0    282.00
23        60 2020-12-23    130     101.0    300.00
24        45 2020-12-24    105     132.0    246.00
25        60 2020-12-25    102     126.0    334.50
26        60 2020-12-26    100     120.0    250.00
27        60 2020-12-27     92     118.0    241.00
28        60 2020-12-28    103     132.0    304.68
29        60 2020-12-29    100     132.0    280.00
30        60 2020-12-30    102     129.0    380.30
31        60 2020-12-31     92     115.0    243.00

**27. round():**

It will round the decimal places.

In [66]:
df.round(2)

C:\Users\Aaditya Raj Pandey\AppData\Local\Temp\ipykernel_12512\2464115032.py:1: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  df.round(2)

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110     130.0    409.10
1         60 2020-12-02    117     145.0    479.00
2         60 2020-12-03    103     135.0    340.00
3         45 2020-12-04    109     175.0    282.40
4         45 2020-12-05    117     148.0    406.00
5         60 2020-12-06    102     127.0    300.00
6         60 2020-12-07    110     136.0    374.00
7         56 2020-12-08    104     134.0    253.30
8         30 2020-12-09    109     133.0    195.10
9         60 2020-12-10     98     124.0    269.00
10        60 2020-12-11    103     147.0    329.30
11        60 2020-12-12    100     120.0    250.70
13        60 2020-12-13    106     128.0    345.30
14        60 2020-12-14    104     132.0    379.30
15        60 2020-12-15     98     123.0    275.00
16        60 2020-12-16     98     120.0    215.20
17        60 2020-12-17    100     120.0    300.00
18        45 2020-12-18     90     112.0    304.68
19        60 2020-12-19    103     123.0    323.00
20        45 2020-12-20     97     125.0    243.00
21        60 2020-12-21    108     131.0    364.20
22        45 2020-12-12    100     119.0    282.00
23        60 2020-12-23    130     101.0    300.00
24        45 2020-12-24    105     132.0    246.00
25        60 2020-12-25    102     126.0    334.50
26        60 2020-12-26    100     120.0    250.00
27        60 2020-12-27     92     118.0    241.00
28        60 2020-12-28    103     132.0    304.68
29        60 2020-12-29    100     132.0    280.00
30        60 2020-12-30    102     129.0    380.30
31        60 2020-12-31     92     115.0    243.00

**28. rename():**

It will rename the Column Header names.

In [67]:
df = df.rename(columns = {
    'Maxpulse':'Max_pulse'
})
df

    Duration       Date  Pulse  Max_pulse  Calories
0         60 2020-12-01    110      130.0    409.10
1         60 2020-12-02    117      145.0    479.00
2         60 2020-12-03    103      135.0    340.00
3         45 2020-12-04    109      175.0    282.40
4         45 2020-12-05    117      148.0    406.00
5         60 2020-12-06    102      127.0    300.00
6         60 2020-12-07    110      136.0    374.00
7         56 2020-12-08    104      134.0    253.30
8         30 2020-12-09    109      133.0    195.10
9         60 2020-12-10     98      124.0    269.00
10        60 2020-12-11    103      147.0    329.30
11        60 2020-12-12    100      120.0    250.70
13        60 2020-12-13    106      128.0    345.30
14        60 2020-12-14    104      132.0    379.30
15        60 2020-12-15     98      123.0    275.00
16        60 2020-12-16     98      120.0    215.20
17        60 2020-12-17    100      120.0    300.00
18        45 2020-12-18     90      112.0    304.68
19        60 2020-12-19    103      123.0    323.00
20        45 2020-12-20     97      125.0    243.00
21        60 2020-12-21    108      131.0    364.20
22        45 2020-12-12    100      119.0    282.00
23        60 2020-12-23    130      101.0    300.00
24        45 2020-12-24    105      132.0    246.00
25        60 2020-12-25    102      126.0    334.50
26        60 2020-12-26    100      120.0    250.00
27        60 2020-12-27     92      118.0    241.00
28        60 2020-12-28    103      132.0    304.68
29        60 2020-12-29    100      132.0    280.00
30        60 2020-12-30    102      129.0    380.30
31        60 2020-12-31     92      115.0    243.00

**29. reset_index():**

It will allow you to drop the existing index and it will create a fresh index for our data.

In [70]:
df = df.reset_index(drop = True)

In [71]:
df

    Duration       Date  Pulse  Max_pulse  Calories
0         60 2020-12-01    110      130.0    409.10
1         60 2020-12-02    117      145.0    479.00
2         60 2020-12-03    103      135.0    340.00
3         45 2020-12-04    109      175.0    282.40
4         45 2020-12-05    117      148.0    406.00
5         60 2020-12-06    102      127.0    300.00
6         60 2020-12-07    110      136.0    374.00
7         56 2020-12-08    104      134.0    253.30
8         30 2020-12-09    109      133.0    195.10
9         60 2020-12-10     98      124.0    269.00
10        60 2020-12-11    103      147.0    329.30
11        60 2020-12-12    100      120.0    250.70
12        60 2020-12-13    106      128.0    345.30
13        60 2020-12-14    104      132.0    379.30
14        60 2020-12-15     98      123.0    275.00
15        60 2020-12-16     98      120.0    215.20
16        60 2020-12-17    100      120.0    300.00
17        45 2020-12-18     90      112.0    304.68
18        60 2020-12-19    103      123.0    323.00
19        45 2020-12-20     97      125.0    243.00
20        60 2020-12-21    108      131.0    364.20
21        45 2020-12-12    100      119.0    282.00
22        60 2020-12-23    130      101.0    300.00
23        45 2020-12-24    105      132.0    246.00
24        60 2020-12-25    102      126.0    334.50
25        60 2020-12-26    100      120.0    250.00
26        60 2020-12-27     92      118.0    241.00
27        60 2020-12-28    103      132.0    304.68
28        60 2020-12-29    100      132.0    280.00
29        60 2020-12-30    102      129.0    380.30
30        60 2020-12-31     92      115.0    243.00

**30. groupby():**

Groupby is used to split the data into Groups, apply a calculation and then combine the result.

**Syntax:**

df.groupby('column_name')['Value_Column'].aggregated_function()

**Q.1) What is the Average Calories Burned For each workout duration ?**

In [72]:
df.groupby('Duration')['Calories'].mean()

Duration
30    195.100000
45    294.013333
56    253.300000
60    316.807826
Name: Calories, dtype: float64

**Q.2) What are the total calories Burned on each data ?**

In [73]:
df.groupby('Date')['Calories'].sum()

Date
2020-12-01    409.10
2020-12-02    479.00
2020-12-03    340.00
2020-12-04    282.40
2020-12-05    406.00
2020-12-06    300.00
2020-12-07    374.00
2020-12-08    253.30
2020-12-09    195.10
2020-12-10    269.00
2020-12-11    329.30
2020-12-12    532.70
2020-12-13    345.30
2020-12-14    379.30
2020-12-15    275.00
2020-12-16    215.20
2020-12-17    300.00
2020-12-18    304.68
2020-12-19    323.00
2020-12-20    243.00
2020-12-21    364.20
2020-12-23    300.00
2020-12-24    246.00
2020-12-25    334.50
2020-12-26    250.00
2020-12-27    241.00
2020-12-28    304.68
2020-12-29    280.00
2020-12-30    380.30
2020-12-31    243.00
Name: Calories, dtype: float64

**Q.3) What is the maximum heart rate for each workout duration ?**

In [75]:
df.groupby('Duration')['Max_pulse'].max()

Duration
30    133.0
45    175.0
56    134.0
60    147.0
Name: Max_pulse, dtype: float64

**31. Export the Cleaned Data:**

In [76]:
import os

In [77]:
os.listdir()

['.ipynb_checkpoints',
 'ambiguous_fitness_dataset.csv',
 'Data Cleaning And Preprocessing 01,02.ipynb',
 'DAX File.xlsx',
 'Matplotlib 01,02,03,04.ipynb',
 'NumPy 01,02,03.ipynb',
 'Pandas 01,02.ipynb',
 'Seaborn 01,02,03,04.ipynb']

In [79]:
df.to_csv("Cleaned File.csv",index = False) #export the cleaned file as a CSV File.

In [80]:
df.to_excel("Cleaned_File.xlsx",index = False) # exporting the cleaned file as a EXCEL File.

In [81]:
os.listdir()

['.ipynb_checkpoints',
 'ambiguous_fitness_dataset.csv',
 'Cleaned File.csv',
 'Cleaned_File.xlsx',
 'Data Cleaning And Preprocessing 01,02.ipynb',
 'DAX File.xlsx',
 'Matplotlib 01,02,03,04.ipynb',
 'NumPy 01,02,03.ipynb',
 'Pandas 01,02.ipynb',
 'Seaborn 01,02,03,04.ipynb']