**What is Pandas ?**

Pandas is a python library that is used to work with the datasets. Datasets can be any format like csv,excel , xml, sql, text, json, etc.

It has functions for analyzing, cleaning, exploring and manipulating the data.

The term "Pandas" has a reference to both "Panel Data" and "Python Data Analysis" and was developed by Wes Mckinnet in 2008.

In [4]:
import pandas as pd

**Data Structures in Pandas:**

In Pandas there are 2-types of Data structures:

- Series
- DataFrame

### Series:

A Pandas series is like a Column in a Table. It is a One-dimensional array holding data of any type.

In [14]:
a = [1,2,"3",True, "India", 3.143]
myvar1 = pd.Series(a)
myvar1

0        1
1        2
2        3
3     True
4    India
5    3.143
dtype: object

**Labels:-**

If nothing else is Specified, the values are labeled with their default index number,First value has index 0, and it goes on.

In [17]:
print(myvar1[0:4:2]) #slicing

0    1
2    3
dtype: object

**Creating a Label:-**

With the index argument, you can name your own labels.

In [18]:
a = [1,2,3,4]
myvar2 = pd.Series(a)
myvar2

0    1
1    2
2    3
3    4
dtype: int64

In [26]:
a[2]

3

In [20]:
myvar2 = pd.Series(a, index = ["W","X","Y","Z"])
myvar2

W    1
X    2
Y    3
Z    4
dtype: int64

In [21]:
index = [f"X{i}" for i in range(1,len(a)+1)]
myvar2 = pd.Series(a, index = index)
myvar2

X1    1
X2    2
X3    3
X4    4
dtype: int64

In [23]:
type(myvar2)

pandas.Series

### DataFrame:

Datasets in Pandas are usually multi-dimensional tables, called as DataFrames. DataFrame is just like a Combination of multiple Series. A Series is Just like a Single Column but the DataFrame is the complete Table.

In [27]:
mydataset = {
    'Cars' : ["BMW","Audi","Volvo","Ford"] ,
    'Year' : [1978, 1975, 1983,1965]
}

In [28]:
myvar = pd.DataFrame(mydataset)
myvar

    Cars  Year
0    BMW  1978
1   Audi  1975
2  Volvo  1983
3   Ford  1965

**iloc:** Indexed based location Fetching. It's Syntax is .iloc[row,column]

In [33]:
myvar.iloc[2]

Cars    Volvo
Year     1983
Name: 2, dtype: object

In [38]:
myvar.iloc[2,0] # better way

'Volvo'

In [37]:
myvar.iloc[2]["Cars"]

'Volvo'

**Customizing the Labels/Indexes:**

In [24]:
myvar3 = pd.DataFrame(mydataset, index = ["A","B","C","D"])
myvar3

    Cars  Year
A    BMW  1978
B   Audi  1975
C  Volvo  1983
D   Ford  1965

**loc:** Labelled Based Value Fetching.

In [43]:
myvar3.loc["C"]

Cars    Volvo
Year     1983
Name: C, dtype: object

In [44]:
myvar3.loc["C","Cars"]

'Volvo'

In [22]:
type(myvar)

pandas.DataFrame

### Locating Files into a DataFrame:

In [1]:
import os

In [2]:
os.getcwd()

'C:\\Users\\Aaditya Raj Pandey\\OneDrive\\Desktop\\Data Analysis and Visualization\\Wed Thu 7 Pm'

In [6]:
df = pd.read_excel('DAX file.xlsx') # if the file is located in the same folder where the Jupyter notebook is opened
df

,Retailer,Retailer ID,Date,Region,State,Beverage Brand,Price per Unit,Units Sold,Revenue,Expenses
0,Sodapop,1185732,2022-01-14,Northeast,New York,Coca-Cola,0.50,12000,6000.0,1982
1,Sodapop,1185732,2022-01-14,Northeast,New York,Diet Coke,0.50,10000,5000.0,1990
2,Sodapop,1185732,2022-01-14,Northeast,New York,Sprite,0.40,10000,4000.0,2979
3,Sodapop,1185732,2022-01-14,Northeast,New York,Fanta,0.45,8500,3825.0,2436
4,Sodapop,1185732,2022-01-14,Northeast,New York,Powerade,0.60,9000,5400.0,1992
...,...,...,...,...,...,...,...,...,...,...
3734,Sodapop,1185732,2022-12-20,Northeast,New Hampshire,Diet Coke,0.65,4000,2600.0,2300
3735,Sodapop,1185732,2022-12-20,Northeast,New Hampshire,Sprite,0.65,3750,2437.5,2202
3736,Sodapop,1185732,2022-12-20,Northeast,New Hampshire,Fanta,0.65,3250,2112.5,2449
3737,Sodapop,1185732,2022-12-20,Northeast,New Hampshire,Powerade,0.75,3250,2437.5,1961
3738,Sodapop,1185732,2022-12-20,Northeast,New Hampshire,Dasani Water,0.80,4250,3400.0,2991

In [9]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [8]:
df

      Retailer  Retailer ID       Date     Region           State  \
0      Sodapop      1185732 2022-01-14  Northeast        New York
1      Sodapop      1185732 2022-01-14  Northeast        New York
2      Sodapop      1185732 2022-01-14  Northeast        New York
3      Sodapop      1185732 2022-01-14  Northeast        New York
4      Sodapop      1185732 2022-01-14  Northeast        New York
5      Sodapop      1185732 2022-01-14  Northeast        New York
6      Sodapop      1185732 2022-02-12  Northeast        New York
7      Sodapop      1185732 2022-02-12  Northeast        New York
8      Sodapop      1185732 2022-02-12  Northeast        New York
9      Sodapop      1185732 2022-02-12  Northeast        New York
10     Sodapop      1185732 2022-02-12  Northeast        New York
11     Sodapop      1185732 2022-02-12  Northeast        New York
12     Sodapop      1185732 2022-03-10  Northeast        New York
13     Sodapop      1185732 2022-03-10  Northeast        New York
14     Sodapop      1185732 2022-03-10  Northeast        New York
15     Sodapop      1185732 2022-03-10  Northeast        New York
16     Sodapop      1185732 2022-03-10  Northeast        New York
17     Sodapop      1185732 2022-03-10  Northeast        New York
18     Sodapop      1185732 2022-04-11  Northeast        New York
19     Sodapop      1185732 2022-04-11  Northeast        New York
20     Sodapop      1185732 2022-04-11  Northeast        New York
21     Sodapop      1185732 2022-04-11  Northeast        New York
22     Sodapop      1185732 2022-04-11  Northeast        New York
23     Sodapop      1185732 2022-04-11  Northeast        New York
24     Sodapop      1185732 2022-05-10  Northeast        New York
25     Sodapop      1185732 2022-05-10  Northeast        New York
26     Sodapop      1185732 2022-05-10  Northeast        New York
27     Sodapop      1185732 2022-05-10  Northeast        New York
28     Sodapop      1185732 2022-05-10  Northeast        New York
29     Sodapop      1185732 2022-05-10  Northeast        New York
30     Sodapop      1185732 2022-06-12  Northeast        New York
31     Sodapop      1185732 2022-06-12  Northeast        New York
32     Sodapop      1185732 2022-06-12  Northeast        New York
33     Sodapop      1185732 2022-06-12  Northeast        New York
34     Sodapop      1185732 2022-06-12  Northeast        New York
35     Sodapop      1185732 2022-06-12  Northeast        New York
36     Sodapop      1185732 2022-07-10  Northeast        New York
37     Sodapop      1185732 2022-07-10  Northeast        New York
38     Sodapop      1185732 2022-07-10  Northeast        New York
39     Sodapop      1185732 2022-07-10  Northeast        New York
40     Sodapop      1185732 2022-07-10  Northeast        New York
41     Sodapop      1185732 2022-07-10  Northeast        New York
42     Sodapop      1185732 2022-08-11  Northeast        New York
43     Sodapop      1185732 2022-08-11  Northeast        New York
44     Sodapop      1185732 2022-08-11  Northeast        New York
45     Sodapop      1185732 2022-08-11  Northeast        New York
46     Sodapop      1185732 2022-08-11  Northeast        New York
47     Sodapop      1185732 2022-08-11  Northeast        New York
48     Sodapop      1185732 2022-09-10  Northeast        New York
49     Sodapop      1185732 2022-09-10  Northeast        New York
50     Sodapop      1185732 2022-09-10  Northeast        New York
51     Sodapop      1185732 2022-09-10  Northeast        New York
52     Sodapop      1185732 2022-09-10  Northeast        New York
53     Sodapop      1185732 2022-09-10  Northeast        New York
54     Sodapop      1185732 2022-10-12  Northeast        New York
55     Sodapop      1185732 2022-10-12  Northeast        New York
56     Sodapop      1185732 2022-10-12  Northeast        New York
57     Sodapop      1185732 2022-10-12  Northeast        New York
58     Sodapop      1185732 2022-10-12  Northeast        New York
59     Sodapop      1185732 2022-10-12  Northeast        New York
60     Sodapop      1185732 2022-11-11  Northeast        New York
61     Sodapop      1185732 2022-11-11  Northeast        New York
62     Sodapop      1185732 2022-11-11  Northeast        New York
63     Sodapop      1185732 2022-11-11  Northeast        New York
64     Sodapop      1185732 2022-11-11  Northeast        New York
65     Sodapop      1185732 2022-11-11  Northeast        New York
66     Sodapop      1185732 2022-12-10  Northeast        New York
67     Sodapop      1185732 2022-12-10  Northeast        New York
68     Sodapop      1185732 2022-12-10  Northeast        New York
69     Sodapop      1185732 2022-12-10  Northeast        New York
70     Sodapop      1185732 2022-12-10  Northeast        New York
71     Sodapop      1185732 2022-12-10  Northeast        New York
72       BevCo      1197831 2022-01-02      South           Texas
73       BevCo      1197831 2022-01-02      South           Texas
74       BevCo      1197831 2022-01-02      South           Texas
75       BevCo      1197831 2022-01-02      South           Texas
76       BevCo      1197831 2022-01-02      South           Texas
77       BevCo      1197831 2022-01-02      South           Texas
78       BevCo      1197831 2022-02-01      South           Texas
79       BevCo      1197831 2022-02-01      South           Texas
80       BevCo      1197831 2022-02-01      South           Texas
81       BevCo      1197831 2022-02-01      South           Texas
82       BevCo      1197831 2022-02-01      South           Texas
83       BevCo      1197831 2022-02-01      South           Texas
84       BevCo      1197831 2022-03-03      South           Texas
85       BevCo      1197831 2022-03-03      South           Texas
86       BevCo      1197831 2022-03-03      South           Texas
87       BevCo      1197831 2022-03-03      South           Texas
88       BevCo      1197831 2022-03-03      South           Texas
89       BevCo      1197831 2022-03-03      South           Texas
90       BevCo      1197831 2022-04-02      South           Texas
91       BevCo      1197831 2022-04-02      South           Texas
92       BevCo      1197831 2022-04-02      South           Texas
93       BevCo      1197831 2022-04-02      South           Texas
94       BevCo      1197831 2022-04-02      South           Texas
95       BevCo      1197831 2022-04-02      South           Texas
96       BevCo      1197831 2022-05-02      South           Texas
97       BevCo      1197831 2022-05-02      South           Texas
98       BevCo      1197831 2022-05-02      South           Texas
99       BevCo      1197831 2022-05-02      South           Texas
100      BevCo      1197831 2022-05-02      South           Texas
101      BevCo      1197831 2022-05-02      South           Texas
102      BevCo      1197831 2022-06-01      South           Texas
103      BevCo      1197831 2022-06-01      South           Texas
104      BevCo      1197831 2022-06-01      South           Texas
105      BevCo      1197831 2022-06-01      South           Texas
106      BevCo      1197831 2022-06-01      South           Texas
107      BevCo      1197831 2022-06-01      South           Texas
108      BevCo      1197831 2022-07-03      South           Texas
109      BevCo      1197831 2022-07-03      South           Texas
110      BevCo      1197831 2022-07-03      South           Texas
111      BevCo      1197831 2022-07-03      South           Texas
112      BevCo      1197831 2022-07-03      South           Texas
113      BevCo      1197831 2022-07-03      South           Texas
114      BevCo      1197831 2022-08-05      South           Texas
115      BevCo      1197831 2022-08-05      South           Texas
116      BevCo      1197831 2022-08-05      South           Texas
117      BevCo      1197831 2022-08-05      South           Texas
118      BevCo      1197831 2022-08-05      South           Texas
119      BevCo      1197831 2022-08-05      South           Texas
120      BevCo      1197831 2022-09-02      South           Texas
121      BevCo      1197831 2022-09-02      South           Texas
122      BevCo      1197831 2022-09-02      South           Texas
123      BevCo      1197831 2022-09-02      South           Texas
124      BevCo      1197831 2022-09-02      South           Texas
125      BevCo      1197831 2022-09-02      South           Texas
126      BevCo      1197831 2022-10-01      South           Texas
127      BevCo      1197831 2022-10-01      South           Texas
128      BevCo      1197831 2022-10-01      South           Texas
129      BevCo      1197831 2022-10-01      South           Texas
130      BevCo      1197831 2022-10-01      South           Texas
131      BevCo      1197831 2022-10-01      South           Texas
132      BevCo      1197831 2022-11-02      South           Texas
133      BevCo      1197831 2022-11-02      South           Texas
134      BevCo      1197831 2022-11-02      South           Texas
135      BevCo      1197831 2022-11-02      South           Texas
136      BevCo      1197831 2022-11-02      South           Texas
137      BevCo      1197831 2022-11-02      South           Texas
138      BevCo      1197831 2022-12-01      South           Texas
139      BevCo      1197831 2022-12-01      South           Texas
140      BevCo      1197831 2022-12-01      South           Texas
141      BevCo      1197831 2022-12-01      South           Texas
142      BevCo      1197831 2022-12-01      South           Texas
143      BevCo      1197831 2022-12-01      South           Texas
144   FizzySip      1128299 2022-01-20       West      California
145   FizzySip      1128299 2022-01-20       West      California
146   FizzySip      1128299 2022-01-20       West      California
147   FizzySip      1128299 2022-01-20       West      California
148   FizzySip      1128299 2022-01-20       West      California
149   FizzySip      1128299 2022-01-20       West      California
150   FizzySip      1128299 2022-02-20       West      California
151   FizzySip      1128299 2022-02-20       West      California
152   FizzySip      1128299 2022-02-20       West      California
153   FizzySip      1128299 2022-02-20       West      California
154   FizzySip      1128299 2022-02-20       West      California
155   FizzySip      1128299 2022-02-20       West      California
156   FizzySip      1128299 2022-03-19       West      California
157   FizzySip      1128299 2022-03-19       West      California
158   FizzySip      1128299 2022-03-19       West      California
159   FizzySip      1128299 2022-03-19       West      California
160   FizzySip      1128299 2022-03-19       West      California
161   FizzySip      1128299 2022-03-19       West      California
162   FizzySip      1128299 2022-04-20       West      California
163   FizzySip      1128299 2022-04-20       West      California
164   FizzySip      1128299 2022-04-20       West      California
165   FizzySip      1128299 2022-04-20       West      California
166   FizzySip      1128299 2022-04-20       West      California
167   FizzySip      1128299 2022-04-20       West      California
168   FizzySip      1128299 2022-05-21       West      California
169   FizzySip      1128299 2022-05-21       West      California
170   FizzySip      1128299 2022-05-21       West      California
171   FizzySip      1128299 2022-05-21       West      California
172   FizzySip      1128299 2022-05-21       West      California
173   FizzySip      1128299 2022-05-21       West      California
174   FizzySip      1128299 2022-06-20       West      California
175   FizzySip      1128299 2022-06-20       West      California
176   FizzySip      1128299 2022-06-20       West      California
177   FizzySip      1128299 2022-06-20       West      California
178   FizzySip      1128299 2022-06-20       West      California
179   FizzySip      1128299 2022-06-20       West      California
180   FizzySip      1128299 2022-07-19       West      California
181   FizzySip      1128299 2022-07-19       West      California
182   FizzySip      1128299 2022-07-19       West      California
183   FizzySip      1128299 2022-07-19       West      California
184   FizzySip      1128299 2022-07-19       West      California
185   FizzySip      1128299 2022-07-19       West      California
186   FizzySip      1128299 2022-08-20       West      California
187   FizzySip      1128299 2022-08-20       West      California
188   FizzySip      1128299 2022-08-20       West      California
189   FizzySip      1128299 2022-08-20       West      California
190   FizzySip      1128299 2022-08-20       West      California
191   FizzySip      1128299 2022-08-20       West      California
192   FizzySip      1128299 2022-09-21       West      California
193   FizzySip      1128299 2022-09-21       West      California
194   FizzySip      1128299 2022-09-21       West      California
195   FizzySip      1128299 2022-09-21       West      California
196   FizzySip      1128299 2022-09-21       West      California
197   FizzySip      1128299 2022-09-21       West      California
198   FizzySip      1128299 2022-10-20       West      California
199   FizzySip      1128299 2022-10-20       West      California
200   FizzySip      1128299 2022-10-20       West      California
201   FizzySip      1128299 2022-10-20       West      California
202   FizzySip      1128299 2022-10-20       West      California
203   FizzySip      1128299 2022-10-20       West      California
204   FizzySip      1128299 2022-11-20       West      California
205   FizzySip      1128299 2022-11-20       West      California
206   FizzySip      1128299 2022-11-20       West      California
207   FizzySip      1128299 2022-11-20       West      California
208   FizzySip      1128299 2022-11-20       West      California
209   FizzySip      1128299 2022-11-20       West      California
210   FizzySip      1128299 2022-12-19       West      California
211   FizzySip      1128299 2022-12-19       West      California
212   FizzySip      1128299 2022-12-19       West      California
213   FizzySip      1128299 2022-12-19       West      California
214   FizzySip      1128299 2022-12-19       West      California
215   FizzySip      1128299 2022-12-19       West      California
216    DreamCo      1189833 2022-01-15       West      California
217    DreamCo      1189833 2022-01-15       West      California
218    DreamCo      1189833 2022-01-15       West      California
219    DreamCo      1189833 2022-01-15       West      California
220    DreamCo      1189833 2022-01-15       West      California
221    DreamCo      1189833 2022-01-15       West      California
222    DreamCo      1189833 2022-02-15       West      California
223    DreamCo      1189833 2022-02-15       West      California
224    DreamCo      1189833 2022-02-15       West      California
225    DreamCo      1189833 2022-02-15       West      California
226    DreamCo      1189833 2022-02-15       West      California
227    DreamCo      1189833 2022-02-15       West      California
228    DreamCo      1189833 2022-03-14       West      California
229    DreamCo      1189833 2022-03-14       West      California
230    DreamCo      1189833 2022-03-14       West      California
231    DreamCo      1189833 2022-03-14       West      California
232    DreamCo      1189833 2022-03-14       West      California
233    DreamCo      1189833 2022-03-14       West      California
234    DreamCo      1189833 2022-04-15       West      California
235    DreamCo      1189833 2022-04-15       West      California
236    DreamCo      1189833 2022-04-15       West      California
237    DreamCo      1189833 2022-04-15       West      California
238    DreamCo      1189833 2022-04-15       West      California
239    DreamCo      1189833 2022-04-15       West      California
240    DreamCo      1189833 2022-05-16       West      California
241    DreamCo      1189833 2022-05-16       West      California
242    DreamCo      1189833 2022-05-16       West      California
243    DreamCo      1189833 2022-05-16       West      California
244    DreamCo      1189833 2022-05-16       West      California
245    DreamCo      1189833 2022-05-16       West      California
246    DreamCo      1189833 2022-06-15       West      California
247    DreamCo      1189833 2022-06-15       West      California
248    DreamCo      1189833 2022-06-15       West      California
249    DreamCo      1189833 2022-06-15       West      California
250    DreamCo      1189833 2022-06-15       West      California
251    DreamCo      1189833 2022-06-15       West      California
252    DreamCo      1189833 2022-07-14       West      California
253    DreamCo      1189833 2022-07-14       West      California
254    DreamCo      1189833 2022-07-14       West      California
255    DreamCo      1189833 2022-07-14       West      California
256    DreamCo      1189833 2022-07-14       West      California
257    DreamCo      1189833 2022-07-14       West      California
258    DreamCo      1189833 2022-08-15       West      California
259    DreamCo      1189833 2022-08-15       West      California
260    DreamCo      1189833 2022-08-15       West      California
261    DreamCo      1189833 2022-08-15       West      California
262    DreamCo      1189833 2022-08-15       West      California
263    DreamCo      1189833 2022-08-15       West      California
264    DreamCo      1189833 2022-09-16       West      California
265    DreamCo      1189833 2022-09-16       West      California
266    DreamCo      1189833 2022-09-16       West      California
267    DreamCo      1189833 2022-09-16       West      California
268    DreamCo      1189833 2022-09-16       West      California
269    DreamCo      1189833 2022-09-16       West      California
270    DreamCo      1189833 2022-10-15       West      California
271    DreamCo      1189833 2022-10-15       West      California
272    DreamCo      1189833 2022-10-15       West      California
273    DreamCo      1189833 2022-10-15       West      California
274    DreamCo      1189833 2022-10-15       West      California
275    DreamCo      1189833 2022-10-15       West      California
276    DreamCo      1189833 2022-11-15       West      California
277    DreamCo      1189833 2022-11-15       West      California
278    DreamCo      1189833 2022-11-15       West      California
279    DreamCo      1189833 2022-11-15       West      California
280    DreamCo      1189833 2022-11-15       West      California
281    DreamCo      1189833 2022-11-15       West      California
282    DreamCo      1189833 2022-12-14       West      California
283    DreamCo      1189833 2022-12-14       West      California
284    DreamCo      1189833 2022-12-14       West      California
285    DreamCo      1189833 2022-12-14       West      California
286    DreamCo      1189833 2022-12-14       West      California
287    DreamCo      1189833 2022-12-14       West      California
288    Sodapop      1185732 2022-01-15    Midwest        Illinois
289    Sodapop      1185732 2022-01-15    Midwest        Illinois
290    Sodapop      1185732 2022-01-15    Midwest        Illinois
291    Sodapop      1185732 2022-01-15    Midwest        Illinois
292    Sodapop      1185732 2022-01-15    Midwest        Illinois
293    Sodapop      1185732 2022-01-15    Midwest        Illinois
294    Sodapop      1185732 2022-02-15    Midwest        Illinois
295    Sodapop      1185732 2022-02-15    Midwest        Illinois
296    Sodapop      1185732 2022-02-15    Midwest        Illinois
297    Sodapop      1185732 2022-02-15    Midwest        Illinois
298    Sodapop      1185732 2022-02-15    Midwest        Illinois
299    Sodapop      1185732 2022-02-15    Midwest        Illinois
300    Sodapop      1185732 2022-03-14    Midwest        Illinois

In [16]:
df1 = pd.read_csv("C://Users//Aaditya Raj Pandey//OneDrive//Desktop//Data Analysis and Visualization//Data Cleaning And Preprocessing//3 30 PM WED-THU//E_Commerce_dataset.csv")
df1

,Order_ID,Customer_Name,Product,Quantity,Price,Order_Date,Delivery_Status
0,O1081,Ivy,T-shirt,1,476.29,2023-03-23,Delivered
1,O1142,Ivy,Watch,1,447.75,2023-05-23,Delivered
2,O1031,Charlie,Laptop,1,239.96,2023-02-01,Cancelled
3,O1029,David,Smartphone,2,206.32,2023-01-30,Delivered
4,O1118,Grace,Camera,5,60.08,2023-04-29,Cancelled
5,NaN,David,Camera,3,218.06,2023-03-02,Cancelled
6,O1093,Jack,Camera,2,47.63,2023-04-04,Delivered
7,O1147,Ivy,Headphones,4,485.27,2023-05-28,Cancelled
8,O1003,Eva,Camera,1,42.08,2023-01-04,Delivered
9,O1068,Grace,Smartphone,3,382.18,2023-03-10,Delivered
10,O1042,Jack,Backpack,4,347.84,2023-02-12,Pending
11,O1138,Frank,Camera,2,482.35,2023-05-19,Cancelled
12,O1078,Alice,Headphones,2,63.82,2023-03-20,Delivered
13,O1075,Jack,Laptop,3,100000,12/05/23,Delivered
14,O1015,Eva,Watch,-3,324.84,2023-01-16,Pending
15,O1019,Bob,Laptop,3,261.51,2023-01-20,Delivered
16,O1030,Ivy,Headphones,5,328.78,12/05/23,Pending
17,O1090,Charlie,Backpack,4,twenty,2023-04-01,Pending
18,O1117,Grace,Smartphone,4,200.6,2023-04-28,Cancelled
19,O1137,Eva,Camera,1,127.33,2023-05-18,Cancelled
20,O1018,Frank,Camera,4,320.41,2023-01-19,Delivered
21,O1012,Helen,Camera,1,228.25,2023-01-13,Pending
22,O1009,Eva,Headphones,2,255.98,2023-01-10,Delivered
23,O1024,Ivy,Smartphone,3,328.36,2023-01-25,Delivered
24,O1069,Ivy,Watch,2,69.5,2023-03-11,Delivered
25,O1131,Grace,Headphones,1,378.1,2023-05-12,Pending
26,O1095,Jack,Shoes,3,NaN,2023-04-06,Pending
27,O1045,Eva,Laptop,5,425.54,2023-02-15,Delivered
28,O1086,Charlie,Shoes,4,177.76,2023-03-28,Delivered
29,O1084,Helen,Shoes,2,235.25,2023-03-26,Pending
30,O1126,David,Watch,2,244.96,2023-05-07,Cancelled
31,O1096,Ivy,Laptop,1,446.1,2023-04-07,Delivered
32,O1122,Charlie,Laptop,3,455.05,2023-05-03,Delivered
33,O1082,Helen,Headphones,5,295.25,2023-03-24,Delivered
34,O1109,Charlie,Backpack,4,60.72,2023-04-20,Delivered
35,O1065,Jack,Camera,3,NaN,2023-03-07,Delivered
36,O1051,Alice,Shoes,1,321.89,2023-02-21,Cancelled
37,O1026,Jack,Shoes,3,301.17,2023-01-27,Delivered
38,O1133,Frank,Laptop,5,481.84,2023-05-14,Pending
39,O1076,Ivy,Laptop,5,25.2,2023-03-18,Pending
40,O1056,Bob,Backpack,4,105.17,2023-02-26,Cancelled
41,O1036,Ivy,Headphones,5,454.57,2023-02-06,Delivered
42,O1124,Alice,Laptop,3,256.46,2023-05-05,Pending
43,O1022,Jack,Watch,4,98.21,2023-01-23,Cancelled
44,O1055,David,Camera,1,155.38,2023-02-25,Pending
45,O1085,Helen,Headphones,-3,160.74,2023-03-27,Cancelled
46,O1011,Helen,Shoes,5,103.14,2023-01-12,Pending
47,O1141,Grace,Camera,5,40.72,2023-05-22,Pending
48,O1066,David,T-shirt,2,225.92,2023-03-08,Cancelled
49,O1119,Ivy,Laptop,2,393.03,2023-04-30,Cancelled
50,O1027,Charlie,Watch,3,471.31,2023-01-28,Delivered
51,O1079,Ivy,Watch,3,173.27,2023-03-21,Cancelled
52,O1144,Alice,Laptop,5,496.62,2023-05-25,Pending
53,O1041,Bob,Watch,1,65.33,2023-02-11,Pending
54,O1004,Grace,Headphones,3,39.55,2023-01-05,Delivered
55,O1032,Eva,T-shirt,4,281.9,2023-02-02,Delivered
56,O1134,Bob,Laptop,1,199.94,2023-05-15,Pending
57,O1143,Grace,Camera,5,273.3,2023-05-24,Cancelled
58,O1067,Helen,Shoes,2,380.42,2023-03-09,Cancelled
59,O1016,Bob,Camera,1,41.75,2023-01-17,Pending
60,O1123,Grace,Smartphone,1,73.37,2023-05-04,Pending
61,O1010,David,Smartphone,3,twenty,2023-01-11,Cancelled
62,O1113,Charlie,Headphones,4,410.14,2023-04-24,Pending
63,O1146,Ivy,Shoes,3,285.85,2023-05-27,Pending
64,O1101,Alice,Smartphone,1,316.74,2023-04-12,Pending
65,NaN,Grace,Headphones,4,383.77,2023-01-01,Pending
66,O1110,Alice,Backpack,4,493.59,2023-04-21,Pending
67,O1064,Bob,Watch,2,466.76,2023-03-06,Pending
68,O1044,Jack,Camera,5,173.11,2023-02-14,Delivered
69,O1097,Grace,Laptop,2,188.44,2023-04-08,Delivered
70,O1028,Grace,Backpack,3,296.23,2023-01-29,Delivered
71,NaN,Ivy,Shoes,1,28.75,05-12-2023,Pending
72,O1104,Helen,Headphones,3,356.47,2023-04-15,Pending
73,O1025,Alice,Shoes,5,100000,2023-01-26,Delivered
74,O1023,Frank,Laptop,3,53.87,2023-01-24,Delivered
75,O1108,Frank,Smartphone,5,59.05,2023-04-19,Pending
76,O1039,David,Smartphone,3,68.37,2023-02-09,Pending
77,O1001,David,Backpack,4,26.91,2023-01-02,Cancelled
78,O1098,Ivy,Camera,5,76.19,2023-04-09,Pending
79,NaN,Grace,Headphones,4,383.77,2023-01-01,Pending
80,O1136,Ivy,Headphones,2,436.93,2023-05-17,Cancelled
81,O1047,David,Headphones,4,410.94,2023-02-17,Delivered
82,O1111,Charlie,Watch,4,199.65,2023-04-22,Delivered
83,O1061,Frank,Headphones,2,198.57,2023-03-03,Delivered
84,O1073,Eva,Camera,1,173.62,2023-03-15,Delivered
85,O1033,Charlie,Laptop,1,471.9,2023-02-03,Pending
86,O1148,David,Laptop,2,271.09,2023-05-29,Delivered
87,O1125,David,Camera,4,100000,2023-05-06,Cancelled
88,O1062,Bob,Laptop,1,392.68,2023-03-04,Delivered
89,O1105,Eva,Shoes,4,54.93,2023-04-16,Pending
90,O1094,Grace,Backpack,2,283.77,2023-04-05,Delivered
91,O1053,Bob,Camera,3,372.83,2023-02-23,Cancelled
92,O1005,Jack,Laptop,1,NaN,2023-01-06,Pending
93,O1127,Eva,Shoes,2,47.03,2023-05-08,Cancelled
94,O1114,Alice,Backpack,5,474.68,2023-04-25,Cancelled
95,O1049,Helen,Smartphone,5,76.72,2023-02-19,Delivered
96,O1035,Eva,Laptop,4,NaN,2023-02-05,Cancelled
97,NaN,Grace,Camera,2,476.03,2023-03-22,Delivered
98,O1077,Ivy,Shoes,2,454.58,2023-03-19,Cancelled
99,O1034,Grace,Camera,5,205.33,2023-02-04,Pending
100,O1046,Bob,Laptop,3,31.17,2023-02-16,Cancelled
101,O1007,Grace,T-shirt,2,247.6,2023-01-08,Cancelled
102,O1043,Ivy,T-shirt,4,54.17,2023-02-13,Cancelled
103,O1070,Helen,Watch,2,453.23,2023-03-12,Cancelled
104,O1112,Eva,Smartphone,5,197.91,2023-04-23,Pending
105,O1091,Alice,Headphones,3,63.78,2023-04-02,Delivered
106,O1083,Alice,Shoes,4,323.28,2023-03-25,Pending
107,O1139,David,Headphones,1,25.83,2023-05-20,Pending
108,NaN,Jack,Shoes,5,485.54,2023-05-21,Delivered
109,O1089,Charlie,Headphones,1,399.96,2023-03-31,Delivered
110,O1008,Helen,Laptop,2,66.96,2023-01-09,Cancelled
111,O1013,Charlie,Backpack,4,211.28,2023-01-14,Delivered
112,O1059,Jack,Headphones,1,495.44,2023-03-01,Cancelled
113,O1132,Charlie,Backpack,4,300.02,2023-05-13,Pending
114,O1003,Eva,Camera,1,42.08,2023-01-04,Delivered
115,O1017,Helen,Camera,5,199.81,2023-01-18,Pending
116,O1038,Bob,Smartphone,4,53.29,2023-02-08,Delivered
117,O1072,Bob,Backpack,1,416.7,2023-03-14,Delivered
118,O1135,Jack,Headphones,2,157.14,2023-05-16,Cancelled
119,O1006,Charlie,Watch,5,357.76,2023-01-07,Pending
120,O1128,Grace,T-shirt,5,77.03,2023-05-09,Pending
121,NaN,Bob,Backpack,2,385.53,05-12-2023,NaN
122,O1002,Helen,Watch,3,75.71,2023-01-03,Cancelled
123,NaN,Jack,Shoes,-3,288.03,12/05/23,Cancelled
124,O1063,Jack,Backpack,2,183.59,2023-03-05,Delivered
125,O1115,Eva,Shoes,4,493.28,2023-04-26,Delivered
126,O1054,Helen,Watch,4,405.67,2023-02-24,Delivered
127,O1107,Helen,Laptop,1,359.0,2023-04-18,Cancelled
128,O1050,Charlie,T-shirt,-3,twenty,2023-02-20,NaN
129,O1002,Helen,Watch,3,75.71,2023-01-03,Cancelled
130,O1058,Frank,Backpack,5,407.28,2023-02-28,Pending
131,O1048,Grace,Watch,1,155.29,2023-02-18,Pending
132,O1088,Helen,Smartphone,4,381.14,2023-03-30,Pending
133,O1021,Alice,Laptop,1,336.17,2023-01-22,Pending
134,O1057,Frank,Shoes,5,380.3,2023-02-27,Delivered
135,O1149,Ivy,Camera,3,322.11,2023-05-30,Delivered
136,O1129,Grace,T-shirt,2,76.41,2023-05-10,Pending
137,O1037,Grace,Laptop,3,113.98,2023-02-07,Cancelled
138,O1145,Alice,Camera,5,55.42,2023-05-26,Cancelled
139,O1001,David,Backpack,4,26.91,2023-01-02,Cancelled
140,O1052,David,Smartphone,5,441.19,2023-02-22,Delivered
141,O1130,David,Camera,5,twenty,2023-05-11,Pending
142,O1103,Grace,Laptop,2,60.37,2023-04-14,Pending
143,O1099,Helen,Camera,2,88.64,2023-04-10,Cancelled
144,O1116,Jack,Camera,3,381.62,2023-04-27,Delivered
145,O1087,Alice,Headphones,5,342.81,2023-03-29,Delivered
146,O1074,Helen,Camera,1,449.85,2023-03-16,Cancelled
147,O1121,Jack,Shoes,2,223.63,2023-05-02,Delivered
148,O1004,Grace,Headphones,3,39.55,2023-01-05,Delivered
149,NaN,Eva,Shoes,1,431.12,2023-01-21,Cancelled
150,O1071,Eva,Headphones,2,262.52,2023-03-13,Pending
151,O1106,Charlie,Laptop,5,414.49,2023-04-17,Cancelled
152,O1014,Frank,Headphones,1,315.61,2023-01-15,Pending
153,O1092,Eva,Shoes,4,257.32,2023-04-03,Cancelled
154,O1102,Grace,Camera,4,68.54,2023-04-13,Pending

In [18]:
df2 = pd.read_csv(r"C:\Users\Aaditya Raj Pandey\OneDrive\Desktop\Data Analysis and Visualization\Data Cleaning And Preprocessing\3 30 PM WED-THU\E_Commerce_dataset.csv")
df2

,Order_ID,Customer_Name,Product,Quantity,Price,Order_Date,Delivery_Status
0,O1081,Ivy,T-shirt,1,476.29,2023-03-23,Delivered
1,O1142,Ivy,Watch,1,447.75,2023-05-23,Delivered
2,O1031,Charlie,Laptop,1,239.96,2023-02-01,Cancelled
3,O1029,David,Smartphone,2,206.32,2023-01-30,Delivered
4,O1118,Grace,Camera,5,60.08,2023-04-29,Cancelled
5,NaN,David,Camera,3,218.06,2023-03-02,Cancelled
6,O1093,Jack,Camera,2,47.63,2023-04-04,Delivered
7,O1147,Ivy,Headphones,4,485.27,2023-05-28,Cancelled
8,O1003,Eva,Camera,1,42.08,2023-01-04,Delivered
9,O1068,Grace,Smartphone,3,382.18,2023-03-10,Delivered
10,O1042,Jack,Backpack,4,347.84,2023-02-12,Pending
11,O1138,Frank,Camera,2,482.35,2023-05-19,Cancelled
12,O1078,Alice,Headphones,2,63.82,2023-03-20,Delivered
13,O1075,Jack,Laptop,3,100000,12/05/23,Delivered
14,O1015,Eva,Watch,-3,324.84,2023-01-16,Pending
15,O1019,Bob,Laptop,3,261.51,2023-01-20,Delivered
16,O1030,Ivy,Headphones,5,328.78,12/05/23,Pending
17,O1090,Charlie,Backpack,4,twenty,2023-04-01,Pending
18,O1117,Grace,Smartphone,4,200.6,2023-04-28,Cancelled
19,O1137,Eva,Camera,1,127.33,2023-05-18,Cancelled
20,O1018,Frank,Camera,4,320.41,2023-01-19,Delivered
21,O1012,Helen,Camera,1,228.25,2023-01-13,Pending
22,O1009,Eva,Headphones,2,255.98,2023-01-10,Delivered
23,O1024,Ivy,Smartphone,3,328.36,2023-01-25,Delivered
24,O1069,Ivy,Watch,2,69.5,2023-03-11,Delivered
25,O1131,Grace,Headphones,1,378.1,2023-05-12,Pending
26,O1095,Jack,Shoes,3,NaN,2023-04-06,Pending
27,O1045,Eva,Laptop,5,425.54,2023-02-15,Delivered
28,O1086,Charlie,Shoes,4,177.76,2023-03-28,Delivered
29,O1084,Helen,Shoes,2,235.25,2023-03-26,Pending
30,O1126,David,Watch,2,244.96,2023-05-07,Cancelled
31,O1096,Ivy,Laptop,1,446.1,2023-04-07,Delivered
32,O1122,Charlie,Laptop,3,455.05,2023-05-03,Delivered
33,O1082,Helen,Headphones,5,295.25,2023-03-24,Delivered
34,O1109,Charlie,Backpack,4,60.72,2023-04-20,Delivered
35,O1065,Jack,Camera,3,NaN,2023-03-07,Delivered
36,O1051,Alice,Shoes,1,321.89,2023-02-21,Cancelled
37,O1026,Jack,Shoes,3,301.17,2023-01-27,Delivered
38,O1133,Frank,Laptop,5,481.84,2023-05-14,Pending
39,O1076,Ivy,Laptop,5,25.2,2023-03-18,Pending
40,O1056,Bob,Backpack,4,105.17,2023-02-26,Cancelled
41,O1036,Ivy,Headphones,5,454.57,2023-02-06,Delivered
42,O1124,Alice,Laptop,3,256.46,2023-05-05,Pending
43,O1022,Jack,Watch,4,98.21,2023-01-23,Cancelled
44,O1055,David,Camera,1,155.38,2023-02-25,Pending
45,O1085,Helen,Headphones,-3,160.74,2023-03-27,Cancelled
46,O1011,Helen,Shoes,5,103.14,2023-01-12,Pending
47,O1141,Grace,Camera,5,40.72,2023-05-22,Pending
48,O1066,David,T-shirt,2,225.92,2023-03-08,Cancelled
49,O1119,Ivy,Laptop,2,393.03,2023-04-30,Cancelled
50,O1027,Charlie,Watch,3,471.31,2023-01-28,Delivered
51,O1079,Ivy,Watch,3,173.27,2023-03-21,Cancelled
52,O1144,Alice,Laptop,5,496.62,2023-05-25,Pending
53,O1041,Bob,Watch,1,65.33,2023-02-11,Pending
54,O1004,Grace,Headphones,3,39.55,2023-01-05,Delivered
55,O1032,Eva,T-shirt,4,281.9,2023-02-02,Delivered
56,O1134,Bob,Laptop,1,199.94,2023-05-15,Pending
57,O1143,Grace,Camera,5,273.3,2023-05-24,Cancelled
58,O1067,Helen,Shoes,2,380.42,2023-03-09,Cancelled
59,O1016,Bob,Camera,1,41.75,2023-01-17,Pending
60,O1123,Grace,Smartphone,1,73.37,2023-05-04,Pending
61,O1010,David,Smartphone,3,twenty,2023-01-11,Cancelled
62,O1113,Charlie,Headphones,4,410.14,2023-04-24,Pending
63,O1146,Ivy,Shoes,3,285.85,2023-05-27,Pending
64,O1101,Alice,Smartphone,1,316.74,2023-04-12,Pending
65,NaN,Grace,Headphones,4,383.77,2023-01-01,Pending
66,O1110,Alice,Backpack,4,493.59,2023-04-21,Pending
67,O1064,Bob,Watch,2,466.76,2023-03-06,Pending
68,O1044,Jack,Camera,5,173.11,2023-02-14,Delivered
69,O1097,Grace,Laptop,2,188.44,2023-04-08,Delivered
70,O1028,Grace,Backpack,3,296.23,2023-01-29,Delivered
71,NaN,Ivy,Shoes,1,28.75,05-12-2023,Pending
72,O1104,Helen,Headphones,3,356.47,2023-04-15,Pending
73,O1025,Alice,Shoes,5,100000,2023-01-26,Delivered
74,O1023,Frank,Laptop,3,53.87,2023-01-24,Delivered
75,O1108,Frank,Smartphone,5,59.05,2023-04-19,Pending
76,O1039,David,Smartphone,3,68.37,2023-02-09,Pending
77,O1001,David,Backpack,4,26.91,2023-01-02,Cancelled
78,O1098,Ivy,Camera,5,76.19,2023-04-09,Pending
79,NaN,Grace,Headphones,4,383.77,2023-01-01,Pending
80,O1136,Ivy,Headphones,2,436.93,2023-05-17,Cancelled
81,O1047,David,Headphones,4,410.94,2023-02-17,Delivered
82,O1111,Charlie,Watch,4,199.65,2023-04-22,Delivered
83,O1061,Frank,Headphones,2,198.57,2023-03-03,Delivered
84,O1073,Eva,Camera,1,173.62,2023-03-15,Delivered
85,O1033,Charlie,Laptop,1,471.9,2023-02-03,Pending
86,O1148,David,Laptop,2,271.09,2023-05-29,Delivered
87,O1125,David,Camera,4,100000,2023-05-06,Cancelled
88,O1062,Bob,Laptop,1,392.68,2023-03-04,Delivered
89,O1105,Eva,Shoes,4,54.93,2023-04-16,Pending
90,O1094,Grace,Backpack,2,283.77,2023-04-05,Delivered
91,O1053,Bob,Camera,3,372.83,2023-02-23,Cancelled
92,O1005,Jack,Laptop,1,NaN,2023-01-06,Pending
93,O1127,Eva,Shoes,2,47.03,2023-05-08,Cancelled
94,O1114,Alice,Backpack,5,474.68,2023-04-25,Cancelled
95,O1049,Helen,Smartphone,5,76.72,2023-02-19,Delivered
96,O1035,Eva,Laptop,4,NaN,2023-02-05,Cancelled
97,NaN,Grace,Camera,2,476.03,2023-03-22,Delivered
98,O1077,Ivy,Shoes,2,454.58,2023-03-19,Cancelled
99,O1034,Grace,Camera,5,205.33,2023-02-04,Pending
100,O1046,Bob,Laptop,3,31.17,2023-02-16,Cancelled
101,O1007,Grace,T-shirt,2,247.6,2023-01-08,Cancelled
102,O1043,Ivy,T-shirt,4,54.17,2023-02-13,Cancelled
103,O1070,Helen,Watch,2,453.23,2023-03-12,Cancelled
104,O1112,Eva,Smartphone,5,197.91,2023-04-23,Pending
105,O1091,Alice,Headphones,3,63.78,2023-04-02,Delivered
106,O1083,Alice,Shoes,4,323.28,2023-03-25,Pending
107,O1139,David,Headphones,1,25.83,2023-05-20,Pending
108,NaN,Jack,Shoes,5,485.54,2023-05-21,Delivered
109,O1089,Charlie,Headphones,1,399.96,2023-03-31,Delivered
110,O1008,Helen,Laptop,2,66.96,2023-01-09,Cancelled
111,O1013,Charlie,Backpack,4,211.28,2023-01-14,Delivered
112,O1059,Jack,Headphones,1,495.44,2023-03-01,Cancelled
113,O1132,Charlie,Backpack,4,300.02,2023-05-13,Pending
114,O1003,Eva,Camera,1,42.08,2023-01-04,Delivered
115,O1017,Helen,Camera,5,199.81,2023-01-18,Pending
116,O1038,Bob,Smartphone,4,53.29,2023-02-08,Delivered
117,O1072,Bob,Backpack,1,416.7,2023-03-14,Delivered
118,O1135,Jack,Headphones,2,157.14,2023-05-16,Cancelled
119,O1006,Charlie,Watch,5,357.76,2023-01-07,Pending
120,O1128,Grace,T-shirt,5,77.03,2023-05-09,Pending
121,NaN,Bob,Backpack,2,385.53,05-12-2023,NaN
122,O1002,Helen,Watch,3,75.71,2023-01-03,Cancelled
123,NaN,Jack,Shoes,-3,288.03,12/05/23,Cancelled
124,O1063,Jack,Backpack,2,183.59,2023-03-05,Delivered
125,O1115,Eva,Shoes,4,493.28,2023-04-26,Delivered
126,O1054,Helen,Watch,4,405.67,2023-02-24,Delivered
127,O1107,Helen,Laptop,1,359.0,2023-04-18,Cancelled
128,O1050,Charlie,T-shirt,-3,twenty,2023-02-20,NaN
129,O1002,Helen,Watch,3,75.71,2023-01-03,Cancelled
130,O1058,Frank,Backpack,5,407.28,2023-02-28,Pending
131,O1048,Grace,Watch,1,155.29,2023-02-18,Pending
132,O1088,Helen,Smartphone,4,381.14,2023-03-30,Pending
133,O1021,Alice,Laptop,1,336.17,2023-01-22,Pending
134,O1057,Frank,Shoes,5,380.3,2023-02-27,Delivered
135,O1149,Ivy,Camera,3,322.11,2023-05-30,Delivered
136,O1129,Grace,T-shirt,2,76.41,2023-05-10,Pending
137,O1037,Grace,Laptop,3,113.98,2023-02-07,Cancelled
138,O1145,Alice,Camera,5,55.42,2023-05-26,Cancelled
139,O1001,David,Backpack,4,26.91,2023-01-02,Cancelled
140,O1052,David,Smartphone,5,441.19,2023-02-22,Delivered
141,O1130,David,Camera,5,twenty,2023-05-11,Pending
142,O1103,Grace,Laptop,2,60.37,2023-04-14,Pending
143,O1099,Helen,Camera,2,88.64,2023-04-10,Cancelled
144,O1116,Jack,Camera,3,381.62,2023-04-27,Delivered
145,O1087,Alice,Headphones,5,342.81,2023-03-29,Delivered
146,O1074,Helen,Camera,1,449.85,2023-03-16,Cancelled
147,O1121,Jack,Shoes,2,223.63,2023-05-02,Delivered
148,O1004,Grace,Headphones,3,39.55,2023-01-05,Delivered
149,NaN,Eva,Shoes,1,431.12,2023-01-21,Cancelled
150,O1071,Eva,Headphones,2,262.52,2023-03-13,Pending
151,O1106,Charlie,Laptop,5,414.49,2023-04-17,Cancelled
152,O1014,Frank,Headphones,1,315.61,2023-01-15,Pending
153,O1092,Eva,Shoes,4,257.32,2023-04-03,Cancelled
154,O1102,Grace,Camera,4,68.54,2023-04-13,Pending

**Some more file reading methods:**

1. pd.read_csv -> For CSV Files
2. pd.read_excel -> For Excel Files
3. pd.read_table -> For Text Files (Like Notepad files)
4. pd.read_json -> For JSON Files ( JavaScript Oject Notations)
5. pd.read_sql -> For SQL Files

In [24]:
df2.head(5) # by default top 5 rows of our dataFrame.

,Order_ID,Customer_Name,Product,Quantity,Price,Order_Date,Delivery_Status
0,O1081,Ivy,T-shirt,1,476.29,2023-03-23,Delivered
1,O1142,Ivy,Watch,1,447.75,2023-05-23,Delivered
2,O1031,Charlie,Laptop,1,239.96,2023-02-01,Cancelled
3,O1029,David,Smartphone,2,206.32,2023-01-30,Delivered
4,O1118,Grace,Camera,5,60.08,2023-04-29,Cancelled

In [27]:
df2.tail() # by default bottom 5 rows of our DataFrame.

,Order_ID,Customer_Name,Product,Quantity,Price,Order_Date,Delivery_Status
150,O1071,Eva,Headphones,2,262.52,2023-03-13,Pending
151,O1106,Charlie,Laptop,5,414.49,2023-04-17,Cancelled
152,O1014,Frank,Headphones,1,315.61,2023-01-15,Pending
153,O1092,Eva,Shoes,4,257.32,2023-04-03,Cancelled
154,O1102,Grace,Camera,4,68.54,2023-04-13,Pending

In [29]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         146 non-null    str
 1   Customer_Name    155 non-null    str
 2   Product          155 non-null    str
 3   Quantity         155 non-null    int64
 4   Price            151 non-null    str
 5   Order_Date       155 non-null    str
 6   Delivery_Status  153 non-null    str
dtypes: int64(1), str(6)
memory usage: 14.7 KB